# docker-compose.yml
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./web/project
      args:
        REACT_APP_API_URL: http://localhost:4000
    ports:
      - "80:80"
    restart: always