# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-ESGK9rSv2A-VjNEccI8HznKXPN8dfe
"""

from fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd
import numpy as np
from parser_openai_edo_url import data_frame_resumen
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost", "http://localhost:80", "*"],  # ajusta si quieres ser más estricto
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class Pregunta(BaseModel):
    texto: str

@app.post("/convocatorias")
def obtener_convocatorias(pregunta: Pregunta):
    try:
        
        df = data_frame_resumen(pregunta.texto)

        # Reemplazar NaN e inf por una cadena amigable
        df_clean = df.replace([np.inf, -np.inf], np.nan).fillna("no info")

        return {"resultados": df_clean.to_dict(orient="records")}

    except Exception as e:
        return {"error": str(e)}
    
    

